    - name: Build site
      run: |
        bundle exec jekyll build --trace --profile
        : > _site/.nojekyll
        echo -n 'beta.ustclug.org' > _site/CNAME
      env:
        JEKYLL_ENV: production
        JEKYLL_GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - name: Deploy to GitHub Pages
      run: |
        CINFO="$(git log -1 --pretty="%an: [%h] %s")"
        pushd _site/ &>/dev/null
        echo -n XxxTang233.github.io > CNAME
        git add -A
        git -c user.name=GitHub -c user.email=noreply@github.com commit \
          -m "Auto deploy from GitHub Actions build ${GITHUB_RUN_NUMBER}" \
          -m "$CINFO"
        git push
        popd &>/dev/null
    - name: Call webhook
      env:
        WEBHOOK_SECRET: ${{ secrets.WEBHOOK_SECRET }}
      run: ruby _scripts/webhook.rb
